language: php
php:
  - '5.6'
  - '7.0'

addons:
  postgresql: "9.3"

  services:
  - postgresql


before_script:
  - travis_retry composer self-update
  - composer install
  - psql -c 'create database app_test;' -U homestead
  - php artisan migrate

script:
 - phpunit --coverage-text --coverage-clover=coverage.clover